---
title: Code of Conduct
author: ""
date: "`r Sys.time()`"
slug: conduct
categories: []
tags: []
summary: ""
---

Everyone in the slack channel is expected to behave professionally and appropriately at all times. Professional and appropriate behaviour involves scientific and ethical integrity, respectful conduct towards others regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearances, race, religion (or lack thereof) or technology choices. We do not tolerate harassment, sexual or otherwise, by anyone. Anyone violating these rules may be expelled from the slack channel. 

Slack channel members agree to at all times:

* Be considerate in speech and actions and respect others.
* Refrain from demeaning, discriminatory, or harassing behavior and speech. 

Harassment is demeaning or threatening behaviour directed at an individual, or a group of people. Harassment includes, but is not limited to,

* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, person's lifestyle choices and practices, physical appearance, age, race, religion (or lack thereof) or technology choices;
* Unwelcome sexual attention and behaviour including inappropriate sexual propositions; unnecessary touching; verbal or written comments or physical actions of a sexual nature; sexually degrading words used to describe an individual; a display of sexually suggestive objects or pictures; or sexually explicit jokes; and 
* Threatening behaviour including bullying, threat of violence, deliberate intimidation, stalking or incitement of violence.

